# Generated by Django 3.1 on 2021-05-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210501_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='time',
        ),
    ]
