# Generated by Django 3.1 on 2021-05-01 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_remove_follower_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
