# Generated by Django 3.1 on 2021-04-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='voice-post'),
        ),
    ]
